export const menuRoles = {
  tongQuan: ["ADMIN", "CUSTOMER"],
  trangCaNhan: [
    "ADMIN",
    "MANAGER",
    "CUSTOMER",
    "STAFF_BUSINESS",
    "STAFF_TECHNICAL",
  ],
  thongBao: [
    "ADMIN",
    "MANAGER",
    "CUSTOMER",
    "STAFF_BUSINESS",
    "STAFF_TECHNICAL",
  ],
  sanPham: ["ADMIN", "MANAGER", "STAFF_BUSINESS", "STAFF_TECHNICAL"],
  khachHang: ["ADMIN", "MANAGER", "STAFF_BUSINESS"],
  donHang: [
    "ADMIN",
    "MANAGER",
    "STAFF_BUSINESS",
    "STAFF_TECHNICAL",
    "CUSTOMER",
  ],
  donHang_khachHang: ["CUSTOMER"],
  congNo: ["ADMIN", "MANAGER", "STAFF_BUSINESS"],
  congNo_khachHang: ["CUSTOMER"],
  baoCao: ["ADMIN"],
  heThong: ["ADMIN", "MANAGER"],
  quanLyTaiKhoan: ["ADMIN", "MANAGER"],
  taiChinh: ["ADMIN", "MANAGER", "STAFF_BUSINESS"],
  pages: ["ADMIN"],
};
